"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Загружаем переменные окружения из .env файла (если есть)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    import warnings
    warnings.warn(
        "DJANGO_SECRET_KEY environment variable is not set! "
        "Using temporary insecure key. SET THIS IN PRODUCTION!",
        RuntimeWarning
    )
    # Temporary fallback - MUST be changed in production
    SECRET_KEY = "django-insecure-TEMPORARY-KEY-change-this-immediately-in-production-settings"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# ALLOWED_HOSTS - безопасная настройка для продакшена
ALLOWED_HOSTS_ENV = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "")

if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]
elif RENDER_EXTERNAL_HOSTNAME:
    # Используем хост из Render, если доступен
    ALLOWED_HOSTS = [RENDER_EXTERNAL_HOSTNAME]
elif DEBUG:
    # В режиме разработки разрешаем локальные хосты
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    # В продакшене без указанных хостов - используем wildcard с предупреждением
    import warnings
    warnings.warn(
        "ALLOWED_HOSTS not set in production! Using wildcard '*' is insecure. "
        "Please set DJANGO_ALLOWED_HOSTS environment variable.",
        RuntimeWarning
    )
    ALLOWED_HOSTS = ["*"]




# Application definition

INSTALLED_APPS = [
    # стандартные
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # WhiteNoise для статики
    'django.contrib.staticfiles',

    # наши приложения
    'accounts',
    'marketplace',
    'payments',
    'notifications',
    'chat',

    # сторонние
    'rest_framework',
    'rest_framework.authtoken',
    'channels',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise для статики
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # i18n middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'marketplace.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Django Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.environ.get('REDIS_HOST', '127.0.0.1'), int(os.environ.get('REDIS_PORT', 6379)))],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=False
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

LANGUAGES = [
    ('ru', 'Русский'),
    ('uz', 'O\'zbek'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise для обслуживания статических файлов в продакшене
# В продакшене (DEBUG=False) используем CompressedStaticFilesStorage
# В разработке используем стандартный storage
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
    # WhiteNoise настройки для продакшена
    WHITENOISE_USE_FINDERS = False  # В продакшене не использовать finders
    WHITENOISE_AUTOREFRESH = False  # В продакшене не автообновлять
    # Максимальное время кеширования статических файлов (1 год)
    WHITENOISE_MAX_AGE = 31536000
    # WhiteNoise автоматически использует STATIC_ROOT, не нужно указывать WHITENOISE_ROOT
else:
    # В разработке используем стандартный storage и finders
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

# Media files (user uploads - avatars, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Кастомная модель пользователя
AUTH_USER_MODEL = 'accounts.User'

# Настройки аутентификации
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Настройка директории для шаблонов уже указана выше в TEMPLATES

# Django REST Framework настройки
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Настройки платежей
PLATFORM_FEE_PERCENTAGE = 10  # Комиссия платформы в процентах

# Настройки Payme
PAYME_LOGIN = os.environ.get('PAYME_LOGIN', 'Paycom')
PAYME_KEY = os.environ.get('PAYME_KEY', '')  # CRITICAL: Must be set in production
if not DEBUG and not PAYME_KEY:
    import warnings
    warnings.warn(
        "PAYME_KEY environment variable is not set! "
        "Payme webhook authentication will fail. SET THIS IN PRODUCTION!",
        RuntimeWarning
    )

# Настройки AI (Google Gemini)
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

# Настройки загрузки файлов
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# ============================================================================
# БЕЗОПАСНОСТЬ ДЛЯ ПРОДАКШЕНА
# ============================================================================
# Проверяем, работаем ли мы за прокси (Render, Heroku и т.д.)
USE_TLS = os.environ.get("USE_TLS", "False") == "True"
IS_BEHIND_PROXY = os.environ.get("IS_BEHIND_PROXY", "True") == "True"  # Render работает за прокси

if not DEBUG:
    # На Render HTTPS обрабатывается на уровне прокси, поэтому не нужно редиректить
    # SECURE_SSL_REDIRECT должен быть False, если работаем за прокси
    SECURE_SSL_REDIRECT = False if IS_BEHIND_PROXY else (os.environ.get("SECURE_SSL_REDIRECT", "False") == "True")
    
    # Настройки для работы за прокси (Render)
    if IS_BEHIND_PROXY:
        # Render передает информацию о HTTPS через заголовки
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        USE_TLS = True
    
    # Безопасные cookies (только если используем HTTPS)
    SESSION_COOKIE_SECURE = USE_TLS
    CSRF_COOKIE_SECURE = USE_TLS
    
    # Другие настройки безопасности
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS настройки - включаем для production
    SECURE_HSTS_SECONDS = 31536000  # 1 год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ============================================================================
# EMAIL НАСТРОЙКИ
# ============================================================================
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@services-marketplace.com')
EMAIL_SUBJECT_PREFIX = '[ServiceHub] '
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# ============================================================================
# ЛОГИРОВАНИЕ
# ============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'marketplace': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Создаем директорию для логов, если её нет
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# ============================================================================
# КЭШИРОВАНИЕ (опционально)
# ============================================================================
CACHE_URL = os.environ.get('CACHE_URL', '')
if CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CACHE_URL,
        }
    }
else:
    # Локальный кэш для разработки
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
