# Generated by Django 5.2.8 on 2025-11-17 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Финальная согласованная цена', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='финальная цена')),
                ('status', models.CharField(choices=[('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending_payment', help_text='Текущий статус сделки', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('client', models.ForeignKey(help_text='Клиент в сделке', on_delete=django.db.models.deletion.CASCADE, related_name='client_deals', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('offer', models.ForeignKey(help_text='Принятое предложение', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='marketplace.offer', verbose_name='предложение')),
                ('specialist', models.ForeignKey(help_text='Специалист в сделке', on_delete=django.db.models.deletion.CASCADE, related_name='specialist_deals', to=settings.AUTH_USER_MODEL, verbose_name='специалист')),
                ('task', models.OneToOneField(help_text='Задача, по которой создана сделка', on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='marketplace.task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'сделка',
                'verbose_name_plural': 'сделки',
                'db_table': 'deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='deals_status_eeb583_idx'), models.Index(fields=['client', 'status'], name='deals_client__999d78_idx'), models.Index(fields=['specialist', 'status'], name='deals_special_cda1f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('text', models.TextField(blank=True, help_text='Текст отзыва (необязательно)', null=True, verbose_name='текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('client', models.ForeignKey(help_text='Клиент, оставивший отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('specialist', models.ForeignKey(help_text='Специалист, которому оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='специалист')),
                ('task', models.ForeignKey(help_text='Задача, по которой оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['specialist', 'rating'], name='reviews_special_832c10_idx'), models.Index(fields=['task'], name='reviews_task_id_6267e2_idx')],
                'unique_together': {('task', 'client')},
            },
        ),
    ]
