# Generated by Django 5.2.8 on 2025-11-17 10:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_review_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='final_price',
            field=models.IntegerField(help_text='Финальная согласованная цена', validators=[django.core.validators.MinValueValidator(0)], verbose_name='финальная цена'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('completed', 'Завершено')], default='pending', help_text='Текущий статус сделки', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='task',
            field=models.ForeignKey(help_text='Задача, по которой создана сделка', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='marketplace.task', verbose_name='задача'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(fields=('task',), name='unique_deal_per_task'),
        ),
    ]
