# Generated by Django 5.2.8 on 2025-11-19 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_escrow_portfolioitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='service_radius_km',
            field=models.PositiveIntegerField(default=0, help_text='Радиус выезда в километрах (0 = не выезжает)', verbose_name='радиус выезда (км)'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='verification_documents',
            field=models.JSONField(blank=True, default=dict, help_text='JSON с информацией о загруженных документах (паспорт, лицензии и т.д.)', verbose_name='документы верификации'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text="Список рабочих дней (например, ['mon', 'tue', 'wed', 'thu', 'fri'])", verbose_name='рабочие дни'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='working_hours_end',
            field=models.TimeField(blank=True, help_text='Время окончания рабочего дня (например, 18:00)', null=True, verbose_name='конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='working_hours_start',
            field=models.TimeField(blank=True, help_text='Время начала рабочего дня (например, 09:00)', null=True, verbose_name='начало рабочего дня'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='works_online',
            field=models.BooleanField(default=False, help_text='Специалист предоставляет услуги онлайн', verbose_name='работает онлайн'),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_structured',
            field=models.BooleanField(default=False, help_text='Задача была создана/структурирована с помощью ИИ', verbose_name='создано через ИИ'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Дедлайн выполнения задачи (если отличается от preferred_date)', null=True, verbose_name='крайний срок'),
        ),
        migrations.AddField(
            model_name='task',
            name='format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Выезд к клиенту'), ('at_specialist', 'У специалиста')], default='offline', help_text='Формат выполнения услуги', max_length=20, verbose_name='формат'),
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта местоположения задачи', max_digits=9, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Долгота местоположения задачи', max_digits=9, null=True, verbose_name='долгота'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Основной адрес клиента', max_length=500, null=True, verbose_name='адрес')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text="JSON с предпочтениями клиента (например, {'preferred_time': 'morning', 'languages': ['ru', 'uz']})", verbose_name='предпочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('favorite_specialists', models.ManyToManyField(blank=True, help_text='Список избранных специалистов', related_name='favorited_by', to=settings.AUTH_USER_MODEL, verbose_name='избранные специалисты')),
                ('user', models.OneToOneField(help_text='Пользователь, которому принадлежит этот профиль', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль клиента',
                'verbose_name_plural': 'профили клиентов',
                'db_table': 'client_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название подкатегории (например, 'Репетитор по математике')", max_length=150, verbose_name='название')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly версия названия', max_length=150, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Описание подкатегории', null=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(help_text='Родительская категория', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='marketplace.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
                'db_table': 'subcategories',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Подкатегория услуги (необязательно)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='marketplace.subcategory', verbose_name='подкатегория'),
        ),
    ]
