# Generated by Django 5.2.8 on 2025-11-19 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_airequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('time_start', models.TimeField(verbose_name='время начала')),
                ('time_end', models.TimeField(verbose_name='время окончания')),
                ('is_available', models.BooleanField(default=True, verbose_name='свободен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('deal', models.ForeignKey(blank=True, help_text='Сделка, под которую забронирован этот слот', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='marketplace.deal', verbose_name='сделка')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL, verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'временной слот',
                'verbose_name_plural': 'временные слоты',
                'db_table': 'time_slots',
                'ordering': ['date', 'time_start'],
                'indexes': [models.Index(fields=['specialist', 'date', 'is_available'], name='time_slots_special_efe2e8_idx'), models.Index(fields=['date', 'is_available'], name='time_slots_date_08725f_idx')],
                'unique_together': {('specialist', 'date', 'time_start')},
            },
        ),
    ]
