# Generated by Django 5.1.1 on 2025-11-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='pending', help_text='Текущий статус сделки', max_length=20, verbose_name='статус'),
        ),
    ]
