# Generated by Django 5.1.1 on 2025-11-22 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_deal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], help_text='День недели (0 - Понедельник, 6 - Воскресенье)', verbose_name='день недели')),
                ('start_time', models.TimeField(verbose_name='время начала')),
                ('end_time', models.TimeField(verbose_name='время окончания')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='повторяющееся')),
            ],
            options={
                'verbose_name': 'слот доступности',
                'verbose_name_plural': 'слоты доступности',
                'db_table': 'availability_slots',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='дата')),
                ('scheduled_time', models.TimeField(verbose_name='время')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='длительность (мин)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='статус')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'db_table': 'bookings',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'элемент портфолио', 'verbose_name_plural': 'портфолио'},
        ),
        migrations.RemoveIndex(
            model_name='portfolioitem',
            name='portfolio_i_special_f3bd88_idx',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='marketplace.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание работы', verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(help_text='Изображение работы', upload_to='portfolio/%Y/%m/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения (меньше - выше)', verbose_name='порядок'),
        ),
        migrations.AddField(
            model_name='availability',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL, verbose_name='специалист'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_client', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='booking',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_specialist', to=settings.AUTH_USER_MODEL, verbose_name='специалист'),
        ),
        migrations.AddField(
            model_name='booking',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.task', verbose_name='задача'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('specialist', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['specialist', 'scheduled_date'], name='bookings_special_0e4773_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='bookings_client__43bbe1_idx'),
        ),
    ]
