# Generated by Django 5.2.8 on 2025-11-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_review_moderation_status_task_moderation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='pending', help_text='Текущий статус сделки', max_length=20, verbose_name='статус'),
        ),
    ]
