# Generated by Django 5.2.8 on 2025-11-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, default='bi-star', help_text="Имя класса иконки Bootstrap Icons (например, 'bi-hammer')", max_length=50, verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='task',
            name='district',
            field=models.CharField(blank=True, help_text='Район города (необязательно)', max_length=100, verbose_name='район'),
        ),
    ]
