# Generated by Django 5.2.8 on 2025-11-27 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_category_icon_name_task_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название конкретной услуги', max_length=200, verbose_name='название услуги')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость услуги', max_digits=10, verbose_name='цена')),
                ('description', models.TextField(blank=True, help_text='Описание услуги (что входит в стоимость)', verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'услуга специалиста',
                'verbose_name_plural': 'услуги специалиста',
                'db_table': 'specialist_services',
                'ordering': ['name'],
            },
        ),
    ]
