# Generated by Django 5.2.8 on 2025-12-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_specialistservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Флаг срочности задачи', verbose_name='срочно'),
        ),
    ]
