# Generated by Django 5.1.1 on 2025-11-21 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_deal_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=255, verbose_name='ID транзакции в Payme')),
                ('time', models.BigIntegerField(verbose_name='время создания транзакции в Payme')),
                ('amount', models.BigIntegerField(verbose_name='сумма (в тийинах)')),
                ('account', models.JSONField(blank=True, null=True, verbose_name='параметры аккаунта')),
                ('create_time', models.BigIntegerField(default=0, verbose_name='время добавления транзакции в БД')),
                ('perform_time', models.BigIntegerField(default=0, verbose_name='время проведения транзакции')),
                ('cancel_time', models.BigIntegerField(default=0, verbose_name='время отмены транзакции')),
                ('state', models.IntegerField(verbose_name='состояние транзакции')),
                ('reason', models.IntegerField(blank=True, null=True, verbose_name='причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payme_transactions', to='marketplace.deal', verbose_name='сделка')),
            ],
            options={
                'verbose_name': 'транзакция Payme',
                'verbose_name_plural': 'транзакции Payme',
            },
        ),
    ]
