# Generated by Django 5.2.8 on 2025-11-17 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название категории (например, 'Ремонт', 'Репетитор')", max_length=100, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly версия названия', max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Описание категории', null=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Биография/описание специалиста', null=True, verbose_name='описание')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Количество лет опыта в сфере', verbose_name='лет опыта')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Почасовая ставка в местной валюте', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='почасовая ставка')),
                ('typical_price_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная типичная цена', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='минимальная цена')),
                ('typical_price_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная типичная цена', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='максимальная цена')),
                ('is_verified', models.BooleanField(default=False, help_text='Верифицирован ли специалист администратором', verbose_name='верифицирован')),
                ('portfolio_links', models.JSONField(blank=True, default=list, help_text="Список URL портфолио (например, ['https://example.com/portfolio'])", verbose_name='ссылки на портфолио')),
                ('active', models.BooleanField(default=True, help_text='Активен ли специалист в данный момент', verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('categories', models.ManyToManyField(blank=True, help_text='Категории услуг, которые предоставляет специалист', related_name='specialists', to='marketplace.category', verbose_name='категории')),
                ('user', models.OneToOneField(help_text='Пользователь, которому принадлежит этот профиль', on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль специалиста',
                'verbose_name_plural': 'профили специалистов',
                'db_table': 'specialist_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок/краткое описание задачи', max_length=200, verbose_name='заголовок')),
                ('description', models.TextField(help_text='Подробное описание задачи', verbose_name='описание')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальный бюджет', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='минимальный бюджет')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальный бюджет', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='максимальный бюджет')),
                ('address', models.CharField(blank=True, help_text='Полный адрес или текст местоположения', max_length=500, null=True, verbose_name='адрес')),
                ('city', models.CharField(help_text='Город, где должна быть выполнена задача', max_length=100, verbose_name='город')),
                ('preferred_date', models.DateField(blank=True, help_text='Предпочтительная дата выполнения услуги', null=True, verbose_name='предпочтительная дата')),
                ('preferred_time', models.TimeField(blank=True, help_text='Предпочтительное время выполнения услуги', null=True, verbose_name='предпочтительное время')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', help_text='Текущий статус задачи', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(help_text='Категория услуги для этой задачи', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='marketplace.category', verbose_name='категория')),
                ('client', models.ForeignKey(help_text='Клиент, создавший эту задачу', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, help_text='Цена, предложенная специалистом', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='предложенная цена')),
                ('message', models.TextField(help_text='Сообщение от специалиста клиенту', verbose_name='сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', help_text='Текущий статус предложения', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('specialist', models.ForeignKey(help_text='Специалист, делающий это предложение', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='специалист')),
                ('task', models.ForeignKey(help_text='Задача, для которой это предложение', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'city'], name='tasks_status_185971_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category', 'status'], name='tasks_categor_273e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['task', 'status'], name='offers_task_id_dce793_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['specialist', 'status'], name='offers_special_11c441_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('task', 'specialist')},
        ),
    ]
