# Generated by Django 5.2.8 on 2025-11-17 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_deal_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('task', 'specialist', 'client')},
        ),
    ]
