# Generated by Django 5.2.8 on 2025-11-19 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_deal_final_price_alter_deal_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма для резервирования', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает резервирования'), ('reserved', 'Средства зарезервированы'), ('locked', 'Средства заблокированы'), ('released', 'Средства переведены'), ('refunded', 'Средства возвращены')], default='pending', help_text='Текущий статус escrow', max_length=20, verbose_name='статус')),
                ('reserved_at', models.DateTimeField(blank=True, help_text='Когда средства были зарезервированы', null=True, verbose_name='дата резервирования')),
                ('released_at', models.DateTimeField(blank=True, help_text='Когда средства были переведены исполнителю', null=True, verbose_name='дата перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('deal', models.OneToOneField(help_text='Сделка, для которой создан escrow', on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='marketplace.deal', verbose_name='сделка')),
            ],
            options={
                'verbose_name': 'escrow',
                'verbose_name_plural': 'escrows',
                'db_table': 'escrows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название работы', max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Описание работы', null=True, verbose_name='описание')),
                ('image', models.ImageField(help_text='Изображение работы', upload_to='portfolio/%Y/%m/%d/', verbose_name='изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше = выше)', verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('specialist', models.ForeignKey(help_text='Специалист, которому принадлежит это портфолио', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'элемент портфолио',
                'verbose_name_plural': 'элементы портфолио',
                'db_table': 'portfolio_items',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['specialist', 'order'], name='portfolio_i_special_f3bd88_idx')],
            },
        ),
    ]
