# Generated by Django 5.2.8 on 2025-11-19 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_specialistprofile_service_radius_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('parse', 'Парсинг текста'), ('estimate', 'Оценка стоимости'), ('rank', 'Ранжирование'), ('schedule', 'Подбор расписания')], help_text='Тип AI запроса', max_length=20, verbose_name='тип запроса')),
                ('input_data', models.JSONField(help_text='JSON с входными данными запроса', verbose_name='входные данные')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='JSON с результатом AI обработки', verbose_name='выходные данные')),
                ('model_used', models.CharField(default='gemini-1.5-flash', help_text='Название использованной AI модели', max_length=50, verbose_name='модель')),
                ('success', models.BooleanField(default=True, help_text='Успешно ли выполнен запрос', verbose_name='успешно')),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке если запрос не удался', null=True, verbose_name='сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, сделавший запрос', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'AI запрос',
                'verbose_name_plural': 'AI запросы',
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_type', 'created_at'], name='ai_requests_request_4d9d49_idx'), models.Index(fields=['user', 'created_at'], name='ai_requests_user_id_4c417c_idx')],
            },
        ),
    ]
