# Generated by Django 5.2.8 on 2025-11-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_clientprofile_favorite_specialists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма комиссии платформы', max_digits=10, verbose_name='комиссия платформы'),
        ),
    ]
