# Generated by Django 5.2.8 on 2025-11-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_deal_commission_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', help_text='Статус модерации отзыва', max_length=20, verbose_name='статус модерации'),
        ),
        migrations.AddField(
            model_name='task',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', help_text='Статус модерации задачи', max_length=20, verbose_name='статус модерации'),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='причина спора')),
                ('description', models.TextField(verbose_name='описание ситуации')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='статус')),
                ('resolution', models.CharField(choices=[('refund_client', 'Возврат клиенту'), ('pay_specialist', 'Выплата специалисту'), ('split', 'Разделение средств'), ('none', 'Без решения')], default='none', max_length=20, verbose_name='решение')),
                ('resolution_comment', models.TextField(blank=True, null=True, verbose_name='комментарий решения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='дата решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='marketplace.deal', verbose_name='сделка')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL, verbose_name='инициатор')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL, verbose_name='кем решено')),
            ],
            options={
                'verbose_name': 'спор',
                'verbose_name_plural': 'споры',
                'ordering': ['-created_at'],
            },
        ),
    ]
