# Generated by Django 5.2.8 on 2025-11-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Пользователь является клиентом', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_specialist',
            field=models.BooleanField(default=False, help_text='Пользователь является специалистом', verbose_name='специалист'),
        ),
    ]
