# Generated by Django 5.2.8 on 2025-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_role_user_is_client_user_is_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='approved', help_text='Статус модерации профиля', max_length=20, verbose_name='статус модерации'),
        ),
    ]
